package com.vcw.falecpv.core.constante;

public enum ExcelEnum {

	ALINEACION_HORIZONTAL_IZQUIERDA, 
	ALINEACION_HORIZONTAL_DERECHA, 
	ALINEACION_HORIZONTAL_CENTRO,
	ALINEACION_VERTICAL_ARRIBA,
	ALINEACION_VERTICAL_CENTRO,
	ALINEACION_VERTICAL_ABAJO;
	
}
